[book]
authors = ["Henry Bergström"]
language = "sv"
src = "src"
title = "Glimåkra Webbutvecklare - Kursbok"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"


[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js", "theme/playground/playground.js", "theme/playground/terminal.js"]
additional-css = ["theme/playground/playground.css"]
