[phases.setup]
nixPkgs = ["mdbook"]

[phases.build]
cmd = "mdbook build"

[phases.start]
cmd = "echo 'Static site built, serving from book directory'"

[variables]
NIXPACKS_BUILD_CMD = "mdbook build"
NIXPACKS_START_CMD = "echo 'Built successfully'"
